# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: packwiz.packwiz
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: packwiz
PackageName: packwiz
License: MIT License
ShortDescription: A command line tool for editing and distributing Minecraft modpacks
ManifestType: defaultLocale
ManifestVersion: 1.5.0
